name: news_app
description: It's a Neuse News thing.
publish_to: none # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5           # Google Auth
  # sign_in_with_apple: ^4.3.0       # Temporarily comment this out
  http: ^1.1.0                     # Fetch RSS feeds
  dart_rss: ^3.0.1                 # Parse RSS feeds
  provider: ^6.0.5                 # State management
  shared_preferences: ^2.2.2       # Local storage
  cached_network_image: ^3.3.0     # Cache news images
  intl: ^0.19.0                    # Date formatting (updated version)
  url_launcher: ^6.2.4            # Open URLs
  cupertino_icons: ^1.0.8          # iOS-style icons
  share_plus: ^7.2.1
  firebase_auth: ^4.15.0           # Correct version
  firebase_core: ^2.13.0           # Correct version
  webview_flutter: ^4.4.2          # For in-app browsing
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  image_picker: ^1.0.7
  flutter_quill: ^10.5.17         # Updated version to resolve conflict
  package_info_plus: ^8.3.0       # Updated version to resolve conflict
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/weather/
  # Add fonts here if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf