name: news_app
description: It's a Neuse News thing.
publish_to: none # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  provider: ^6.0.5
  google_sign_in: ^6.1.5           # Google Auth
  # sign_in_with_apple: ^4.3.0       # Temporarily comment this out
  http: ^1.1.0                     # Fetch RSS feeds
  dart_rss: ^3.0.1                 # Parse RSS feeds
  shared_preferences: ^2.2.2       # Local storage
  cached_network_image: ^3.3.0     # Cache news images
  intl: ^0.19.0                    # Date formatting (updated version)
  url_launcher: ^6.3.1            # Open URLs
  cupertino_icons: ^1.0.8          # iOS-style icons
  share_plus: ^7.2.1
  webview_flutter: ^4.4.2          # Update to the latest version instead of 3.0.4
  firebase_storage: ^11.6.6
  image_picker: ^1.0.4
  # file_picker: ^5.3.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  flutter_quill: ^10.5.17         # Updated version to resolve conflict
  package_info_plus: ^8.3.0       # Updated version to resolve conflict
  table_calendar: ^3.0.9
  flutter_stripe: ^10.0.0         # Add these to your existing dependencies
  # Add these dependencies
  cloud_functions: ^4.5.13
  flutter_credit_card: ^4.0.1
  fl_chart: ^0.61.0 # Use the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Add this line

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/weather/
  # Add fonts here if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf