// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpp3rB0_hJLEd14oNLEZMjOIEI8dZK-q8',
    appId: '1:236600949564:android:1290ec24f72f09c482fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    databaseURL: 'https://neuse-news-df5fd-default-rtdb.firebaseio.com',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLGdDTvwCFYmMF486cEGfiRgDqLZyP62Y',
    appId: '1:236600949564:ios:8bc6bc5c6066c0da82fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    databaseURL: 'https://neuse-news-df5fd-default-rtdb.firebaseio.com',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
    iosClientId: '236600949564-nrl089v9mqt33l2sfpdmdttangdtr01a.apps.googleusercontent.com',
    iosBundleId: 'com.wordnerd.neusenews',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByB7dt5n1W6W-3bZIXkndlt_w_34MrvQc',
    appId: '1:236600949564:web:0599a1e31416837082fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    authDomain: 'neuse-news-df5fd.firebaseapp.com',
    databaseURL: 'https://neuse-news-df5fd-default-rtdb.firebaseio.com',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLGdDTvwCFYmMF486cEGfiRgDqLZyP62Y',
    appId: '1:236600949564:ios:347d18f932f1358d82fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    databaseURL: 'https://neuse-news-df5fd-default-rtdb.firebaseio.com',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
    iosClientId: '236600949564-eclf8t63s95aaasic4emeol55eh32hdt.apps.googleusercontent.com',
    iosBundleId: 'n',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByB7dt5n1W6W-3bZIXkndlt_w_34MrvQc',
    appId: '1:236600949564:web:d87ddd799ca7e12b82fc39',
    messagingSenderId: '236600949564',
    projectId: 'neuse-news-df5fd',
    authDomain: 'neuse-news-df5fd.firebaseapp.com',
    databaseURL: 'https://neuse-news-df5fd-default-rtdb.firebaseio.com',
    storageBucket: 'neuse-news-df5fd.firebasestorage.app',
  );

}